Repository LG-CNS-2-FINAL-PROJECT-FINANCE/FrontEnd, pull requests merged in 2025-08, with the labels that each got.

#8 [feature/frontend-8/header] Footer, Header 제작
  .idea/.gitignore
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/zzogaemall.iml
  package-lock.json
  package.json
  public/assets/bull.png
  public/assets/logo.png
  public/assets/pig.png
  src/App.css
  src/App.js
  src/App.test.js
  src/index.css
  src/layout/AdminLayout.js
  src/layout/Footer/AdminFooter.js
  src/layout/Footer/Footer.js
  src/layout/Header/AdminHeader.js
  src/layout/Header/Header.js
  src/layout/Layout.js
  src/logo.svg
  src/pages/common/ScrollToTop.js
  tailwind.config.js
Labels: 📚PR

#10 [feature/frontend-10/homepage] 홈페이지, 로그인페이지 제작
  package-lock.json
  package.json
  postcss.config.js
  public/assets/dancing_bull.gif
  public/assets/graph.png
  public/assets/logo.png
  public/assets/startingpage_1.jpg
  public/assets/startingpage_2.jpg
  public/assets/startingpage_3.jpg
  public/assets/startingpage_4.jpg
  src/App.js
  src/index.css
  src/index.js
  src/pages/Home.js
  src/pages/Login.js
  tailwind.config.js
Labels: 📚PR

#17 [feature/frontend-17/button] 버튼 컴포넌트 구현, 스타팅 페이지 컴포넌트화
  src/App.js
  src/component/StartingProjectCard.js
  src/component/StartingTopProjectSection.js
  src/component/button.js
  src/layout/Header/Header.js
  src/layout/admin/AdminFooter.js
  src/layout/admin/AdminHeader.js
  src/layout/admin/AdminLayout.js
  src/layout/user/Footer.js
  src/layout/user/Header.js
  src/layout/user/Layout.js
  src/pages/Home.js
Labels: 🎉Feature

#19 [feature/frontend-19/investment] investment 조회 사이트 구현
  src/App.js
  src/component/InvestmentCard.js
  src/component/InvestmentSection.js
  src/component/Searchbar.js
  src/component/StartingProjectCard.js
  src/pages/Home.js
  src/pages/investment/investmentList.js
Labels: 🎉Feature

#23 [feature/frontend-23/loginpage] 로그인 페이지 구현
  package-lock.json
  package.json
  src/App.js
  src/index.js
  src/layout/user/Header.js
  src/pages/Home.js
  src/pages/Login.js
  src/pages/LoginDetail_1.js
  src/pages/LoginDetail_2.js
  src/pages/LoginDetail_3.js
  src/pages/LoginDetail_4.js
  src/pages/LoginDetail_5.js
  src/pages/LoginDetail_6.js
Labels: 📚PR

#31 [feature/frontend-31/Header] 헤더 로그인 비로그인 변경
  package-lock.json
  package.json
  src/layout/user/Header.jsx
  tailwind.config.js
Labels: 📚PR

#40 [feature/frontend-28/market] 마켓페이지 화면 구현
  package-lock.json
  package.json
  src/App.jsx
  src/component/Ballpit.jsx
  src/component/MarketCard.jsx
  src/index.css
  src/pages/market/Market.jsx
  src/pages/market/MarketDetail.jsx
  src/pages/market/SalesChart.jsx
Labels: 📚PR

#43 [feature/frontend-43/header] 사용자 선택에 따른 role 기능 구현
  package-lock.json
  package.json
  src/App.jsx
  src/layout/user/Header.jsx
  src/pages/Role/RoleSelectionPage.jsx
  src/pages/investment/InvestmentComponent/TiltedCard.jsx
  src/pages/login/LoginDetail_6.jsx
Labels: 📚PR

#54 [feature/frontend-54/market] PR Market Page의 모달 화면 및 탭 화면 구현
  src/pages/investment/InvestmentComponent/InvestmentDescription.jsx
  src/pages/investment/InvestmentComponent/InvestmentFiles.jsx
  src/pages/investment/InvestmentComponent/InvestmentProgress.jsx
  src/pages/investment/InvestmentComponent/InvestmentSummary.jsx
  src/pages/market/MarketDetail.jsx
  src/pages/market/SalesChart.jsx
  src/pages/market/TradeHistory.jsx
  src/pages/market/modals/MarketPurchaseModal.jsx
  src/pages/market/modals/MarketSellModal.jsx
Labels: 📚PR

#60 [feature/frontend-60/codeRefactoring]: PR
  package-lock.json
  package.json
  src/api/axiosInstance.js
  src/api/user_api.js
  src/component/Ballpit.jsx
  src/component/ScrollLock.jsx
  src/component/button.jsx
  src/component/useScrollLock.js
  src/pages/asset/modals/AssetCheckModal.jsx
  src/pages/asset/modals/AssetDepositModal.jsx
  src/pages/asset/modals/AssetWithdrawModal.jsx
  src/pages/investment/InvestmentComponent/InvestmentModal.jsx
  src/pages/investment/InvestmentComponent/ReportModal.jsx
  src/pages/market/modals/MarketPurchaseModal.jsx
  src/pages/market/modals/MarketSellModal.jsx
Labels: 📚PR

#61 [feature/frontend-61/adminLogin] 다중작업
  .gitignore
  public/assets/adminlogo.png
  src/App.jsx
  src/api/loginaxiosInstance.js
  src/component/button.jsx
  src/context/AuthContext.jsx
  src/index.js
  src/layout/admin/AdminHeader.jsx
  src/layout/admin/AdminLayout.jsx
  src/pages/admin/UserManagement.jsx
  src/pages/admin/adminComponent/AdminSidebar.jsx
  src/pages/admin/login/AdminLogin.jsx
Labels: 📚PR

#70 [Feature/frontend 69/Theme-Color] 테마 색상 변경
  package-lock.json
  package.json
  src/App.jsx
  src/component/InvestmentCard.jsx
  src/context/ThemeContext.jsx
  src/layout/user/Header.jsx
  src/pages/Role/RoleSelectionPage.jsx
  src/pages/investment/InvestmentComponent/InvestmentModal.jsx
  src/pages/investment/InvestmentComponent/InvestmentProgress.jsx
  src/pages/investment/InvestmentComponent/InvestmentSummary.jsx
  src/pages/investment/InvestmentComponent/ReportModal.jsx
  src/pages/investment/investmentList.jsx
Labels: 🪄design

#74 [hotfix/frontend-74/]폴더명 수정
  src/App.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/Role/RoleSelectionPage.jsx
  src/pages/investment/investmentDetail.jsx
  src/pages/investment/investment_component/InvestmentDescription.jsx
  src/pages/investment/investment_component/InvestmentFiles.jsx
  src/pages/investment/investment_component/InvestmentModal.jsx
  src/pages/investment/investment_component/InvestmentProgress.jsx
  src/pages/investment/investment_component/InvestmentSummary.jsx
  src/pages/investment/investment_component/ReportModal.jsx
  src/pages/investment/investment_component/TiltedCard.jsx
  src/pages/market/MarketDetail.jsx
Labels: 🔥hoxfix

#84 [feature/Frontend-84/AdminPage] 게시물 관리자 페이지 수정
  src/App.jsx
  src/pages/admin/postManagement/PostDetailModal.jsx
  src/pages/admin/postManagement/PostManagement.jsx
Labels: 📚PR

#88 [refactor/frontend-75/adminpage]포스트 상태 관리 수정
  src/pages/admin/postManagement/PostDetailModal.jsx
  src/pages/admin/postManagement/PostManagement.jsx
Labels: 📚PR

#92 [feature/frontend-92/investment] investment api 연결
  src/api/admin_project_api.js
  src/api/project_api.js
  src/pages/admin/postManagement/PostManagement.jsx
  src/pages/investment/investmentDetail.jsx
  src/pages/investment/investmentList.jsx
  src/pages/investment/investment_component/InvestmentFiles.jsx
  src/pages/mypage/AccountManagement.jsx
  src/pages/mypage/EditInfo.jsx
  src/pages/mypage/MyFavorites.jsx
  src/pages/mypage/MyInvestments.jsx
  src/pages/mypage/MyPage.jsx
  src/pages/mypage/MyReports.jsx
Labels: 📚PR

#93 [feature/frontend-93/EditRequet] 프로젝트 수정 요청 추가
  src/App.jsx
  src/pages/mypage/MyEditRequest.jsx
  src/pages/mypage/MyPage.jsx
  src/pages/mypage/my_page_component/EditRequestList.jsx
  src/pages/mypage/my_page_component/EditRequestPreview.jsx
  src/pages/mypage/my_page_component/data/editRequestData.js
Labels: 📚PR

#97 [feature/frontend-97/AdminHeader] 토큰에 따라 이동되는 주소창 변경
  src/context/AuthContext.jsx
  src/layout/admin/AdminHeader.jsx
Labels: 📚PR

#103 [feature/frontend-103/assetApiConnection] Asset API 연동
  src/App.jsx
  src/api/asset_api.js
  src/api/axiosInstance.js
  src/api/user_api.js
  src/component/SearchBar.jsx
  src/layout/user/Header.jsx
  src/layout/user/Layout.jsx
  src/lib/useUser.js
  src/pages/Home.jsx
  src/pages/asset/Asset.jsx
  src/pages/asset/AssetHome.jsx
  src/pages/asset/MyAsset.jsx
  src/pages/asset/modals/AssetCheckModal.jsx
  src/pages/asset/modals/AssetDepositModal.jsx
  src/pages/asset/modals/AssetWithdrawModal.jsx
  src/pages/login/KakaoConfirm.jsx
  src/pages/login/Login.jsx
  src/pages/login/LoginDetail_1.jsx
  src/pages/login/LoginDetail_2.jsx
  src/pages/login/LoginDetail_3.jsx
  src/pages/login/LoginDetail_6.jsx
  src/pages/role/RoleSelectionPage.jsx
Labels: 📚PR

#114 [feature/frontend-114/assetApiConnection] Asset Page Api Connection
  src/api/asset_api.js
  src/api/market_api.js
  src/api/user_api.js
  src/layout/user/Header.jsx
  src/lib/toKSTDateTime.js
  src/pages/asset/Asset.jsx
  src/pages/asset/AssetHome.jsx
  src/pages/asset/MyAsset.jsx
  src/pages/asset/modals/AssetCheckModal.jsx
  src/pages/mypage/AccountManagement.jsx
Labels: 📚PR

#124 [feature/frontend-124/adminPage] 숨김 버튼 추가(작동X 여기는 Request라서 만약 작동하게 하려면 새로 페이지를 제작해야함)
  src/api/admin_project_api.js
  src/context/AuthContext.jsx
  src/pages/admin/postManagement/PostDetailModal.jsx
  src/pages/admin/postManagement/PostHoldModal.jsx
Labels: 📚PR

#131 [feature/frontedend-132/investmentApi] 상품 투자 API 연결
  src/api/asset_api.js
  src/api/favorites_api.js
  src/api/investment_api.js
  src/api/project_api.js
  src/pages/investment/investmentDetail.jsx
  src/pages/investment/investment_component/InvestmentCancelModal.jsx
  src/pages/investment/investment_component/InvestmentModal.jsx
  src/pages/investment/investment_component/InvestmentSummary.jsx
  src/pages/login/LoginDetail_2.jsx
  src/pages/market/MarketDetail.jsx
Labels: 📚PR
